import {IconName} from '../components/atoms/IconRegistry';

export const CATEGORY_ICONS: IconName[] = [
  // Food & Dining
  'utensils',
  'utensils-crossed',
  'coffee',
  'pizza',
  'sandwich',
  'wine',
  'beer',
  'soup',
  'cooking-pot',
  'apple',
  'cherry',
  'grape',
  'banana',
  'carrot',
  'beef',
  'fish',
  'egg',
  'milk',
  'ice-cream',
  'croissant',
  'salad',
  'cookie',
  'cake',
  'cake-slice',
  'candy',
  'popcorn',
  'wheat',
  'citrus',
  'leafy-green',

  // Transport
  'car',
  'car-front',
  'bus',
  'train',
  'tram-front',
  'plane',
  'plane-takeoff',
  'plane-landing',
  'bike',
  'ship',
  'sailboat',
  'fuel',
  'parking-circle',
  'truck',
  'ambulance',
  'navigation',
  'map-pin',
  'map',
  'compass',
  'route',

  // Shopping
  'shopping-cart',
  'shopping-bag',
  'package',
  'package-open',
  'tag',
  'tags',
  'store',
  'shirt',
  'watch',
  'gem',
  'crown',
  'gift',
  'percent',
  'badge-percent',

  // Finance
  'wallet',
  'landmark',
  'banknote',
  'receipt',
  'piggy-bank',
  'trending-up',
  'trending-down',
  'hand-coins',
  'coins',
  'circle-dollar-sign',
  'credit-card',
  'calculator',
  'arrow-up-circle',
  'arrow-down-circle',

  // Home & Utilities
  'house',
  'building',
  'building-2',
  'lightbulb',
  'zap',
  'droplet',
  'droplets',
  'flame',
  'wind',
  'wifi',
  'phone',
  'smartphone',
  'tv',
  'monitor',
  'laptop',
  'gamepad-2',
  'plug',
  'cable',
  'thermometer',
  'air-vent',
  'bath',
  'bed-double',
  'sofa',
  'lamp',
  'door-open',
  'key',
  'lock',
  'shield-check',
  'shield',

  // Health & Wellness
  'heart',
  'heart-pulse',
  'activity',
  'pill',
  'stethoscope',
  'syringe',
  'bandaid',
  'hospital',
  'cross',
  'brain',
  'dumbbell',
  'person-standing',
  'footprints',
  'glasses',
  'smile',
  'moon',
  'sun',
  'umbrella',

  // Entertainment
  'music',
  'music-2',
  'headphones',
  'film',
  'clapperboard',
  'camera',
  'image',
  'palette',
  'brush',
  'scissors',
  'sparkles',
  'party-popper',
  'drama',
  'ticket',
  'dice-5',
  'puzzle',
  'blocks',
  'radio',
  'mic',

  // Education & Work
  'book',
  'book-open',
  'book-marked',
  'notebook',
  'notebook-pen',
  'graduation-cap',
  'school',
  'file-text',
  'briefcase',
  'badge-check',
  'award',
  'trophy',
  'medal',
  'target',
  'pen-tool',
  'ruler',
  'presentation',
  'newspaper',

  // Pets & Animals
  'paw-print',
  'cat',
  'dog',
  'bird',
  'bug',
  'fish',
  'rabbit',
  'squirrel',
  'snail',
  'turtle',

  // Nature & Outdoors
  'trees',
  'tree-deciduous',
  'tree-pine',
  'flower',
  'flower-2',
  'sprout',
  'clover',
  'leaf',
  'mountain',
  'mountain-snow',
  'waves',
  'tent',
  'campfire',
  'flashlight',
  'backpack',
  'luggage',
  'globe',
  'earth',
  'sunrise',
  'sunset',
  'cloud',
  'snowflake',
  'star',
  'sparkle',

  // Communication
  'message-circle',
  'message-square',
  'mail',
  'send',
  'bell',
  'bell-ring',
  'megaphone',

  // People & Social
  'users',
  'user',
  'baby',
  'handshake',
  'heart-handshake',
  'thumbs-up',

  // Tech
  'code',
  'terminal',
  'database',
  'server',
  'cpu',
  'printer',
  'qr-code',

  // Miscellaneous
  'clock',
  'timer',
  'hourglass',
  'alarm',
  'repeat',
  'circle-dot',
  'circle',
  'shapes',
  'flag',
  'bookmark',
  'pin',
  'paperclip',
  'link',
  'anchor',
  'wrench',
  'hammer',
  'paintbrush',
  'box',
  'archive',
  'inbox',
  'settings',
  'cog',
  'help-circle',
  'info',
  'alert-circle',
  'verified',
];

export const CATEGORY_ICON_SEARCH_ALIASES: Partial<Record<IconName, string[]>> = {
  utensils: ['餐饮', '吃饭', '饭', '午饭', '晚饭', '早餐', '食物', '餐厅'],
  'utensils-crossed': ['餐饮', '吃饭', '饭店', '餐厅'],
  coffee: ['咖啡', '饮品', '奶茶', '瑞幸'],
  pizza: ['披萨', '快餐', '餐饮'],
  sandwich: ['三明治', '早餐', '快餐'],
  soup: ['汤', '餐饮', '午餐', '晚餐'],
  'cooking-pot': ['做饭', '买菜', '餐饮'],
  car: ['交通', '汽车', '打车', '出租车', '出行'],
  bus: ['交通', '公交', '巴士', '出行'],
  train: ['交通', '火车', '高铁', '出行'],
  'tram-front': ['交通', '地铁', '轻轨', '出行'],
  plane: ['交通', '飞机', '机票', '旅行', '出行'],
  bike: ['交通', '自行车', '骑行', '出行'],
  fuel: ['交通', '加油', '油费', '汽车'],
  'map-pin': ['位置', '地图', '出行', '地点'],
  'shopping-cart': ['购物', '超市', '买东西'],
  'shopping-bag': ['购物', '衣服', '商场'],
  store: ['商店', '便利店', '购物'],
  shirt: ['衣服', '服饰', '购物'],
  gift: ['礼物', '人情', '红包'],
  wallet: ['钱包', '收入', '工资', '财务'],
  banknote: ['现金', '工资', '收入', '钱'],
  receipt: ['账单', '发票', '收据', '报销'],
  'piggy-bank': ['存钱', '储蓄', '理财'],
  'trending-up': ['投资', '收益', '理财', '收入'],
  'hand-coins': ['收入', '工资', '报销', '兼职'],
  house: ['住房', '房租', '家', '房子'],
  lightbulb: ['电费', '水电', '生活'],
  droplet: ['水费', '水电', '生活'],
  flame: ['燃气', '煤气', '生活'],
  wifi: ['网络', '宽带', '通信'],
  phone: ['电话', '通信', '手机'],
  smartphone: ['手机', '通信', '数码'],
  heart: ['医疗', '健康'],
  'heart-pulse': ['医疗', '健康', '体检'],
  pill: ['药', '药品', '医疗'],
  stethoscope: ['医生', '医院', '医疗'],
  hospital: ['医院', '医疗', '看病'],
  dumbbell: ['运动', '健身', '健康'],
  music: ['娱乐', '音乐'],
  film: ['电影', '娱乐'],
  camera: ['摄影', '娱乐', '相机'],
  'gamepad-2': ['游戏', '娱乐'],
  ticket: ['门票', '电影', '演出', '娱乐'],
  book: ['教育', '书', '学习'],
  'book-open': ['教育', '读书', '学习'],
  'graduation-cap': ['教育', '学费', '学习'],
  school: ['学校', '教育', '学习'],
  briefcase: ['工作', '办公', '兼职'],
  'paw-print': ['宠物'],
  cat: ['猫', '宠物'],
  dog: ['狗', '宠物'],
  trees: ['自然', '公园', '户外'],
  mountain: ['旅游', '旅行', '户外'],
  luggage: ['旅行', '旅游', '行李'],
  globe: ['旅行', '旅游', '全球'],
  users: ['家庭', '朋友', '人情'],
  user: ['用户', '个人'],
  baby: ['孩子', '母婴'],
  handshake: ['人情', '合作'],
  code: ['代码', '开发', '技术'],
  printer: ['打印', '办公'],
  clock: ['时间'],
  circle: ['其他', '默认'],
  shapes: ['其他', '分类', '默认'],
  settings: ['设置'],
};
